Repository openshift/prometheus-operator, pull requests merged in 2020-04, with the labels that each got.

#60 Bug 1805833: Tighten permissions related to CRD create/update
  Documentation/rbac.md
  Documentation/user-guides/getting-started.md
  bundle.yaml
  example/rbac/prometheus-operator/prometheus-operator-cluster-role.yaml
  jsonnet/prometheus-operator/prometheus-operator.libsonnet
Labels: approved, bugzilla/valid-bug, cherry-pick-approved, lgtm

#63 CARRY: OWNERS: add component
  OWNERS
Labels: approved, lgtm

#64 Bump to v0.38.1
  CHANGELOG.md
  Documentation/api.md
  Documentation/rbac.md
  Documentation/user-guides/getting-started.md
  VERSION
  bundle.yaml
  example/non-rbac/prometheus-operator.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_thanosrulers.yaml
  example/rbac/prometheus-operator/prometheus-operator-cluster-role-binding.yaml
  example/rbac/prometheus-operator/prometheus-operator-cluster-role.yaml
  example/rbac/prometheus-operator/prometheus-operator-deployment.yaml
  example/rbac/prometheus-operator/prometheus-operator-service-account.yaml
  example/rbac/prometheus-operator/prometheus-operator-service-monitor.yaml
  example/rbac/prometheus-operator/prometheus-operator-service.yaml
  jsonnet/prometheus-operator/prometheus-operator.libsonnet
  jsonnet/prometheus-operator/thanosruler-crd.libsonnet
  pkg/alertmanager/statefulset.go
  pkg/apis/monitoring/v1/bindata.go
  pkg/apis/monitoring/v1/thanos_types.go
  pkg/prometheus/rules.go
  pkg/thanos/rules.go
  pkg/thanos/statefulset.go
  pkg/thanos/statefulset_test.go
Labels: approved, lgtm

#65 Add TLS config for prometheus-operator
  cmd/operator/main.go
  cmd/operator/main_test.go
  go.mod
  go.sum
  pkg/listwatch/listwatch.go
  pkg/listwatch/namespace_denylist.go
  pkg/listwatch/namespace_denylist_test.go
  pkg/operator/server.go
  pkg/operator/server_test.go
  pkg/prometheus/operator.go
  test/e2e/main_test.go
  test/framework/framework.go
  test/framework/secret.go
  vendor/github.com/brancz/kube-rbac-proxy/LICENSE
  vendor/github.com/brancz/kube-rbac-proxy/pkg/tls/reloader.go
  vendor/k8s.io/component-base/LICENSE
  vendor/k8s.io/component-base/cli/flag/ciphersuites_flag.go
  vendor/k8s.io/component-base/cli/flag/colon_separated_multimap_string_string.go
  vendor/k8s.io/component-base/cli/flag/configuration_map.go
  vendor/k8s.io/component-base/cli/flag/flags.go
  vendor/k8s.io/component-base/cli/flag/langle_separated_map_string_string.go
  vendor/k8s.io/component-base/cli/flag/map_string_bool.go
  vendor/k8s.io/component-base/cli/flag/map_string_string.go
  vendor/k8s.io/component-base/cli/flag/namedcertkey_flag.go
  vendor/k8s.io/component-base/cli/flag/noop.go
  vendor/k8s.io/component-base/cli/flag/omitempty.go
  vendor/k8s.io/component-base/cli/flag/sectioned.go
  vendor/k8s.io/component-base/cli/flag/string_flag.go
  vendor/k8s.io/component-base/cli/flag/tristate.go
  vendor/modules.txt
Labels: approved, lgtm

#61 Bug 1805834: Tighten permissions related to CRD create/update
  Documentation/rbac.md
  Documentation/user-guides/getting-started.md
  bundle.yaml
  example/rbac/prometheus-operator/prometheus-operator-cluster-role.yaml
  jsonnet/prometheus-operator/prometheus-operator.libsonnet
Labels: approved, bugzilla/valid-bug, lgtm

#67 Bug 1829501: fix TLS cli parameters
  cmd/operator/main.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm
