Repository openshift/prometheus-operator, pull requests merged in 2020-08, with the labels that each got.

#83 Bug 1867510: fix CVP issues due to incorrect labels set
  Dockerfile.config-reloader.ocp
  Dockerfile.ocp
Labels: approved, bugzilla/severity-low, bugzilla/valid-bug, lgtm

#82 Bug 1856189: pkg/listwatch: err out with multiple resource versions in List
  pkg/listwatch/listwatch.go
Labels: approved, bugzilla/severity-high, bugzilla/valid-bug, lgtm

#85 Bug 1869732: fix secret and configmap references for TLS config
  OWNERS
  pkg/apis/monitoring/v1/types.go
  pkg/apis/monitoring/v1/types_test.go
  test/e2e/prometheus_test.go
Labels: approved, bugzilla/severity-medium, bugzilla/valid-bug, lgtm
