Repository openshift/prometheus-operator, pull requests merged in 2020-01, with the labels that each got.

#49 Update OWNERS file
  OWNERS
Labels: approved, lgtm, size/M

#48 Dockerfile.ocp: update Go to 1.13
  Dockerfile.ocp
Labels: approved, lgtm, size/XS

#51 Bump to 0.35.0
  .gitignore
  .promu.yml
  CHANGELOG.md
  Documentation/api.md
  Documentation/compatibility.md
  Documentation/thanos.md
  Documentation/user-guides/getting-started.md
  Documentation/user-guides/linting.md
  Makefile
  README.md
  VERSION
  cmd/lint/Dockerfile
  cmd/operator/main.go
  example/prometheus-operator-crd/monitoring.coreos.com_podmonitors.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_prometheuses.yaml
  example/prometheus-operator-crd/monitoring.coreos.com_servicemonitors.yaml
  example/user-guides/getting-started/prometheus-admin-api.yaml
  example/user-guides/getting-started/prometheus-pod-monitor.yaml
  example/user-guides/getting-started/prometheus-service-monitor.yaml
  jsonnet/prometheus-operator/podmonitor-crd.libsonnet
  jsonnet/prometheus-operator/prometheus-crd.libsonnet
  jsonnet/prometheus-operator/prometheus-operator.libsonnet
  jsonnet/prometheus-operator/servicemonitor-crd.libsonnet
  pkg/admission/admission_test.go
  pkg/alertmanager/operator.go
  pkg/alertmanager/statefulset.go
  pkg/alertmanager/statefulset_test.go
  pkg/apis/monitoring/v1/bindata.go
  pkg/apis/monitoring/v1/types.go
  pkg/operator/operator.go
  pkg/prometheus/operator.go
  pkg/prometheus/promcfg.go
  pkg/prometheus/promcfg_test.go
  pkg/prometheus/statefulset.go
  pkg/prometheus/statefulset_test.go
  scripts/travis-push-docker-image.sh
Labels: approved, lgtm, size/XL
